/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface BusinessCreateInput {
  data: {
    name: string;
  };
}

export interface BusinessPagination {
  /**
   * Limit results per request, max 500. must be used with skip
   */
  limit?: number;
  /**
   * Skips results per request. must be used with limit
   */
  skip?: number;
}

export interface BusinessSearchInput {
  pagination?: BusinessPagination;
  searchBy?: {
    appUserId?: number;
    id?: number;
    name?: string;
  };
}

export interface BusinessUpdateInput {
  data: {
    name?: string;
  };
  searchBy: {
    id: number;
  };
}
