/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UserCreateInput {
  data: {
    email: string;
    password: string;
  };
}

export interface UserSearchInput {
  searchBy?: {
    email?: string;
  };
}
