/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ProductPhotoCreateInput {
  data: {
    image: string;
    productId: number;
  };
}

export interface ProductPhotoSearchInput {
  searchBy?: {
    imageId?: string;
    productId?: number;
  };
}
